name = "Numenor"
author = "Fuze"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c95472d30d7280cea53587a01ae140c7f89bf9327ef6afda7f9749d8fea927f"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
